# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: satellite.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='satellite.proto',
  package='satellite',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fsatellite.proto\x12\tsatellite\"\x1c\n\x05\x45vent\x12\x13\n\x07\x64\x65posit\x18\x01 \x03(\x01\x42\x02\x10\x01\"&\n\x03Run\x12\x1f\n\x05\x65vent\x18\x01 \x03(\x0b\x32\x10.satellite.Eventb\x06proto3')
)




_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='satellite.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deposit', full_name='satellite.Event.deposit', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=58,
)


_RUN = _descriptor.Descriptor(
  name='Run',
  full_name='satellite.Run',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='event', full_name='satellite.Run.event', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=98,
)

_RUN.fields_by_name['event'].message_type = _EVENT
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['Run'] = _RUN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
  DESCRIPTOR = _EVENT,
  __module__ = 'satellite_pb2'
  # @@protoc_insertion_point(class_scope:satellite.Event)
  ))
_sym_db.RegisterMessage(Event)

Run = _reflection.GeneratedProtocolMessageType('Run', (_message.Message,), dict(
  DESCRIPTOR = _RUN,
  __module__ = 'satellite_pb2'
  # @@protoc_insertion_point(class_scope:satellite.Run)
  ))
_sym_db.RegisterMessage(Run)


_EVENT.fields_by_name['deposit']._options = None
# @@protoc_insertion_point(module_scope)
