# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: thunderstorm.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='thunderstorm.proto',
  package='thunderstorm',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x12thunderstorm.proto\x12\x0cthunderstorm\"O\n\x0e\x43ylinderIdList\x12\x0f\n\x07\x65ventId\x18\x01 \x01(\x05\x12,\n\ncylinderId\x18\x02 \x03(\x0b\x32\x18.thunderstorm.CylinderId\"\x85\x01\n\nCylinderId\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tparent_id\x18\x02 \x01(\x05\x12\x10\n\x08particle\x18\x03 \x01(\x05\x12\x0e\n\x06\x65nergy\x18\x04 \x01(\x01\x12\r\n\x05theta\x18\x05 \x01(\x01\x12\x0e\n\x06radius\x18\x06 \x01(\x01\x12\t\n\x01z\x18\x07 \x01(\x01\x12\x0c\n\x04time\x18\x08 \x01(\x01\"Y\n\x14ParticleDetectorList\x12\x0f\n\x07\x65ventId\x18\x01 \x01(\x05\x12\x30\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\".thunderstorm.ParticleDetectorData\"e\n\x14ParticleDetectorData\x12\x10\n\x08particle\x18\x01 \x01(\x05\x12\x0e\n\x06\x65nergy\x18\x02 \x01(\x01\x12\r\n\x05theta\x18\x03 \x01(\x01\x12\x0e\n\x06radius\x18\x04 \x01(\x01\x12\x0c\n\x04time\x18\x05 \x01(\x01\x62\x06proto3'
)




_CYLINDERIDLIST = _descriptor.Descriptor(
  name='CylinderIdList',
  full_name='thunderstorm.CylinderIdList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='eventId', full_name='thunderstorm.CylinderIdList.eventId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cylinderId', full_name='thunderstorm.CylinderIdList.cylinderId', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=115,
)


_CYLINDERID = _descriptor.Descriptor(
  name='CylinderId',
  full_name='thunderstorm.CylinderId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='thunderstorm.CylinderId.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parent_id', full_name='thunderstorm.CylinderId.parent_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='particle', full_name='thunderstorm.CylinderId.particle', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='energy', full_name='thunderstorm.CylinderId.energy', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='theta', full_name='thunderstorm.CylinderId.theta', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='radius', full_name='thunderstorm.CylinderId.radius', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='thunderstorm.CylinderId.z', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='thunderstorm.CylinderId.time', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=251,
)


_PARTICLEDETECTORLIST = _descriptor.Descriptor(
  name='ParticleDetectorList',
  full_name='thunderstorm.ParticleDetectorList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='eventId', full_name='thunderstorm.ParticleDetectorList.eventId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='thunderstorm.ParticleDetectorList.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=342,
)


_PARTICLEDETECTORDATA = _descriptor.Descriptor(
  name='ParticleDetectorData',
  full_name='thunderstorm.ParticleDetectorData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='particle', full_name='thunderstorm.ParticleDetectorData.particle', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='energy', full_name='thunderstorm.ParticleDetectorData.energy', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='theta', full_name='thunderstorm.ParticleDetectorData.theta', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='radius', full_name='thunderstorm.ParticleDetectorData.radius', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='thunderstorm.ParticleDetectorData.time', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=344,
  serialized_end=445,
)

_CYLINDERIDLIST.fields_by_name['cylinderId'].message_type = _CYLINDERID
_PARTICLEDETECTORLIST.fields_by_name['data'].message_type = _PARTICLEDETECTORDATA
DESCRIPTOR.message_types_by_name['CylinderIdList'] = _CYLINDERIDLIST
DESCRIPTOR.message_types_by_name['CylinderId'] = _CYLINDERID
DESCRIPTOR.message_types_by_name['ParticleDetectorList'] = _PARTICLEDETECTORLIST
DESCRIPTOR.message_types_by_name['ParticleDetectorData'] = _PARTICLEDETECTORDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CylinderIdList = _reflection.GeneratedProtocolMessageType('CylinderIdList', (_message.Message,), {
  'DESCRIPTOR' : _CYLINDERIDLIST,
  '__module__' : 'thunderstorm_pb2'
  # @@protoc_insertion_point(class_scope:thunderstorm.CylinderIdList)
  })
_sym_db.RegisterMessage(CylinderIdList)

CylinderId = _reflection.GeneratedProtocolMessageType('CylinderId', (_message.Message,), {
  'DESCRIPTOR' : _CYLINDERID,
  '__module__' : 'thunderstorm_pb2'
  # @@protoc_insertion_point(class_scope:thunderstorm.CylinderId)
  })
_sym_db.RegisterMessage(CylinderId)

ParticleDetectorList = _reflection.GeneratedProtocolMessageType('ParticleDetectorList', (_message.Message,), {
  'DESCRIPTOR' : _PARTICLEDETECTORLIST,
  '__module__' : 'thunderstorm_pb2'
  # @@protoc_insertion_point(class_scope:thunderstorm.ParticleDetectorList)
  })
_sym_db.RegisterMessage(ParticleDetectorList)

ParticleDetectorData = _reflection.GeneratedProtocolMessageType('ParticleDetectorData', (_message.Message,), {
  'DESCRIPTOR' : _PARTICLEDETECTORDATA,
  '__module__' : 'thunderstorm_pb2'
  # @@protoc_insertion_point(class_scope:thunderstorm.ParticleDetectorData)
  })
_sym_db.RegisterMessage(ParticleDetectorData)


# @@protoc_insertion_point(module_scope)
