/npm/geometry/type gdml
/npm/geometry/gdml ../gdml/empty.gdml
/npm/thunderstorm/physics standard
/npm/thunderstorm/stacking one_generation
/npm/thunderstorm/energy/cut 0.01
/vis/open OGL
/control/saveHistory
#/vis/viewer/set/background white
/vis/drawVolume worlds
/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate
#/vis/scene/add/axes
/vis/scene/add/date
/vis/scene/add/hits

/gps/particle e-
/gps/direction 0 0 -1
/gps/ene/mono 100 MeV
/run/beamOn 10
exit