/npm/geometry/type gdml
/npm/geometry/gdml ../gdml/NeutronFullAtmosphere.gdml
#/npm/geometry/gdml ../gdml/SpaceCraftFullAtmosphere.gdml
/npm/visualization true
/npm/thunderstorm/physics withoutEmStandard
/npm/thunderstorm/minimal_energy 10.0 MeV
/npm/thunderstorm/stacking/electron false
/npm/thunderstorm/stacking/positron false
/npm/thunderstorm/stacking/gamma false
/npm/thunderstorm/stacking/neutron true
/npm/thunderstorm/stacking/save_gamma false
/npm/thunderstorm/stacking/save_electron false
/npm/thunderstorm/stacking/save_neutron false
/npm/thunderstorm/tracking/save_gamma false
/npm/thunderstorm/tracking/save_electron false

/gps/particle neutron
/gps/position 0.0 0.0 80000.0 meter
/gps/direction 0 0 1
/gps/ene/mono 100.0 MeV
#/run/beamOn 10000
exit