/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package satellite

import tornadofx.*


class MyApp : App(MainView::class) {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    launch<MyApp>(args)
//    println(MyApp().greeting)
}
